import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Clapperboard, PlayIcon } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <header className="p-8 border-b flex justify-between">
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Button>
              <Clapperboard />
            </Button>
            Next Movie
          </h1>
          <form className="flex gap-1 items-center">
            <Input placeholder="Search..." />
            <Button>Search</Button>
          </form>
        </header>
        <div className="flex flex-1">
          <aside className="p-4 border-r flex flex-col gap-2 min-w-50">
            <Button variant="outline" className="justify-start">
              <PlayIcon />
              All Movies
            </Button>
            <Button>All Movies</Button>
            <Button>Action</Button>
            <Button>Drama</Button>
            <Button>Animation</Button>
          </aside>
          <main className="flex-1 p-4"> {children}</main>
        </div>
      </body>
    </html>
  );
}
